In [70]:
import numpy as np
import matplotlib.pyplot as plt
import csv 

In [71]:
filepath='/Housing Price data set.csv'

# **Storing the value**

In [72]:
price=[]
area=[]
bedroom=[]
bathroom=[]
count=0
with open(filepath, mode ='r') as file:     
   csvFile = csv.reader(file) 
   for lines in csvFile:
     if count==0:
       count=count+1
       continue
     price.append(int(float(lines[1])))
     area.append(int(lines[2]))
     bedroom.append(int(lines[3]))
     bathroom.append(int(lines[4]))

In [73]:
m= round(0.7*len(price))
n=4
X1=np.array(area)
X2=np.array(bedroom)
X3=np.array(bathroom)
Y=np.array(price)

# **Training data and Testing data**

In [74]:
X_train1=X1[:m]
X_train2=X2[:m]
X_train3=X3[:m]
Y_train=Y[:m]

X_test1=X1[m+1:]
X_test2=X2[m+1:]
X_test3=X3[m+1:]
Y_test=Y[m+1:]

X_train0=np.ones(m,dtype=int)
X_test0=np.ones(len(X_test1),dtype=int)


In [75]:
X_train=[]
for i  in range(m):
  col=[]
  col.append(X_train0[i])
  col.append(X_train1[i])
  col.append(X_train2[i])
  col.append(X_train3[i])
  X_train.append(col)
X_bar=np.array(X_train)
X=np.array([X_train0,X_train1,X_train2,X_train3])



# **Batch Gradient Descent Algorithm Without Regularization**

In [76]:
def Batch_Gradient_descent_algo(X,Y_train):
  iteration=1000
  m=X[0].size
  learning_rate=0.0000000001
  theta=np.ones(len(X),dtype=int)
  for i in range(iteration):
    y_pre=np.dot(theta.T,X)
    theta=theta-learning_rate*(1.0/m)*np.dot(y_pre-Y_train,X.T)

  return theta

# **Stochastic Gradient Descent Algorithm Without Regularization**

In [77]:
def combine(X,Y_train):
  cc=[]
  for i in range(len(X)):
    col=[]
    col.append(X[i][0])
    col.append(X[i][1])
    col.append(X[i][2])
    col.append(X[i][3])
    col.append(Y_train[i])
    cc.append(col)
  
  cc=np.array(cc)
  return cc


In [78]:
def split_shuffle(matrix):
  X=[]
  Y=[]
  for i in range(len(matrix)):
    col=[]
    col.append(matrix[i][0])
    col.append(matrix[i][1])
    col.append(matrix[i][2])
    col.append(matrix[i][3])
    X.append(col)
    Y.append(matrix[i][4])
  X=np.array(X)
  Y=np.array(Y)
  return X,Y

In [79]:
def Stochastic_Gradient_descent_algo(X,Y_train):
  shuffle_matrix=combine(X,Y_train)
  np.random.shuffle(shuffle_matrix)
  X,Y_train=split_shuffle(shuffle_matrix)
  m=len(X)
  iteration=1000
  learning_rate=0.0000000001
  thetas=np.ones(X[0].size,dtype=float)

  for it  in range(iteration):
    for i in range(m):
      predic= 1.0*(thetas[0]*X[i][0] + thetas[1]*X[i][1] + thetas[2]*X[i][2] +thetas[3]*X[i][3] - Y_train[i])

      thata0=thetas[0]-1.0*learning_rate*(predic)*X[i][0]
      thata1=thetas[1]-1.0*learning_rate*(predic)*X[i][1]
      thata2=thetas[2]-1.0*learning_rate*(predic)*X[i][2]
      thata3=thetas[3]-1.0*learning_rate*(predic)*X[i][3]

      thetas[0]=thata0
      thetas[1]=thata1
      thetas[2]=thata2
      thetas[3]=thata3
  return thetas

# **Accuracy Prediction**

In [80]:
X_test=[]
for i  in range(len(X_test1)):
  col=[]
  col.append(X_test0[i])
  col.append(X_test1[i])
  col.append(X_test2[i])
  col.append(X_test3[i])
  X_test.append(col)
X_test=np.array(X_test)

In [81]:
def error(theta,Y_test,X_test):
  Y_predic=X_test.dot(theta)   
  error_diff=np.subtract(Y_test,Y_predic)
  abserror_diff=np.absolute(error_diff)
  absolute_error=np.divide(abserror_diff,Y_test)
  mean_ab_error=np.mean(absolute_error)
  return mean_ab_error*100

# **Mini Batch Gradient Descent Algorithm Without Regularization**

In [82]:
def get_batches(X,y,batch_size,i):
    X_batch = X[i:i+batch_size,:]
    y_batch = y[i:i+batch_size]    
    return X_batch, y_batch

In [83]:
def Mini_Batch_Gradient_descent_algo(X,Y_train):
  batch_size=10
  num_batches = int(X.shape[0]/batch_size) 
  theta=np.ones(X[0].size,dtype=float)
  # print(num_batches)
  alpha=0.000000001
  for i in range(0,num_batches):
    X_batch, y_batch = get_batches(X,Y_train,batch_size,i)
    predic = np.dot(X_batch,theta)
    theta = theta - alpha * np.dot(X_batch.T,predic - y_batch)/batch_size
  
  thet=[]
  thet.append(theta[0])
  thet.append(theta[1])
  thet.append(theta[2])
  thet.append(theta[3])
  
  thet=np.array(thet)
  return thet

# **MAIN without Regularization**

In [84]:
print("               WITHOUT REGULARIZATION                  ")
print(" ")
batch_theta=Batch_Gradient_descent_algo(X,Y_train)
print("Theta Value for Batch Gradient descent Algorihtm Without Regularization")
print(batch_theta)
print("")
error_batch_gda=error(batch_theta,Y_test,X_test)
print("Accuracy Prediction for Batch Gradient descent Algorithm Without Regularization")
print(error_batch_gda)

print("--------------------------------------------------------------")
print(" ")
stochastic_theta=Stochastic_Gradient_descent_algo(X_bar,Y_train)
print("Theta Value for Stochastic Gradient descent Algorihtm Without Regularization")
print(stochastic_theta)
print(" ")
error_stochastic_gda=error(stochastic_theta,Y_test,X_test)
print("Accuracy Prediction for Stochastic Gradient descent Algorithm Without Regularization")
print(error_stochastic_gda)

print("--------------------------------------------------------------")
print(" ")
mini_batch_theta=Mini_Batch_Gradient_descent_algo(X_bar,Y_train)
print("Theta Value for Mini Batch Gradient descent Algorihtm Without Regularization")
print(mini_batch_theta)
print(" ")
error_mini_batch=error(mini_batch_theta,Y_test,X_test)
print("Accuracy Prediction for Mini Batch Gradient descent Algorithm Without Regularization")
print(error_mini_batch)

               WITHOUT REGULARIZATION                  
 
Theta Value for Batch Gradient descent Algorihtm Without Regularization
[ 1.0023332  11.72948415  1.00742127  1.00350479]

Accuracy Prediction for Batch Gradient descent Algorithm Without Regularization
30.229953002026335
--------------------------------------------------------------
 
Theta Value for Stochastic Gradient descent Algorihtm Without Regularization
[ 1.16626562 12.37331381  1.65830149  1.37097262]
 
Accuracy Prediction for Stochastic Gradient descent Algorithm Without Regularization
29.956567369151966
--------------------------------------------------------------
 
Theta Value for Mini Batch Gradient descent Algorihtm Without Regularization
[1.00133967 6.96105709 1.00368276 1.00170685]
 
Accuracy Prediction for Mini Batch Gradient descent Algorithm Without Regularization
47.159202904283795


# **Batch Gradient Descent Algorithm with Regularization**

In [85]:
def Batch_Gradient_descent_algo_regularization(X,Y_train):
  iteration=1000
  m=X[0].size
  learning_rate=0.0000000001
  lambd=50000000
  theta=np.ones(len(X),dtype=int)
  for i in range(iteration):
    y_pre=np.dot(theta.T,X)
    theta=theta-learning_rate*(1.0/m)*np.dot(y_pre-Y_train,X.T)- ((1.0*lambd*learning_rate)/m)*theta

  return theta

# **Stochastic Gradient Descent Algorithm With Regularization**

In [86]:
def Stochastic_Gradient_descent_algo_regularization(X,Y_train):
  shuffle_matrix=combine(X,Y_train)
  np.random.shuffle(shuffle_matrix)
  X,Y_train=split_shuffle(shuffle_matrix)
  m=len(X)
  iteration=1000
  learning_rate=0.0000000001
  lambd=50000000
  thetas=np.ones(X[0].size,dtype=float)

  for it  in range(iteration):
    for i in range(m):
      predic= 1.0*(thetas[0]*X[i][0] + thetas[1]*X[i][1] + thetas[2]*X[i][2] +thetas[3]*X[i][3] - Y_train[i])

      thata0=thetas[0]-1.0*learning_rate*(predic)*X[i][0] 
      thata1=thetas[1]-1.0*learning_rate*(predic)*X[i][1] - thetas[1]*((1.0*learning_rate*lambd)/m)
      thata2=thetas[2]-1.0*learning_rate*(predic)*X[i][2] - thetas[2]*((1.0*learning_rate*lambd)/m)
      thata3=thetas[3]-1.0*learning_rate*(predic)*X[i][3] - thetas[3]*((1.0*learning_rate*lambd)/m)

      thetas[0]=thata0
      thetas[1]=thata1
      thetas[2]=thata2
      thetas[3]=thata3
  return thetas

# **Mini Batch Gradient Descent Algorithm With Regularization**

In [87]:
def Mini_Batch_Gradient_descent_algo_regularization(X,Y_train):
  batch_size=10
  num_batches = int(X.shape[0]/batch_size) 
  theta=np.ones(X[0].size,dtype=float)
  # print(num_batches)
  alpha=0.000000001
  lambd=5000000
  for i in range(0,num_batches):
    X_batch, y_batch = get_batches(X,Y_train,batch_size,i)
    predic = np.dot(X_batch,theta)
    theta = theta - alpha*(1.0/batch_size) * np.dot(X_batch.T,predic - y_batch) -((1.0*lambd*alpha)/batch_size)*theta
  
  thet=[]
  thet.append(theta[0])
  thet.append(theta[1])
  thet.append(theta[2])
  thet.append(theta[3])
  
  thet=np.array(thet)
  return thet

# **MAIN with Regularization**

In [88]:
print("                   WITH REGULARIZATION                     ")
print(" ")
batch_theta_regulari=Batch_Gradient_descent_algo_regularization(X,Y_train)
print("Theta Value for Batch Gradient descent Algorihtm With Regularization")
print(batch_theta_regulari)
print("")
error_batch_gda_regulari=error(batch_theta_regulari,Y_test,X_test)
print("Accuracy Prediction for Batch Gradient descent Algorithm With Regularization")
print(error_batch_gda_regulari)

print("--------------------------------------------------------------")
print(" ")
stochastic_theta_regulari=Stochastic_Gradient_descent_algo_regularization(X_bar,Y_train)
print("Theta Value for Stochastic Gradient descent Algorihtm With Regularization")
print(stochastic_theta_regulari)
print(" ")
error_stochastic_gda_regulari=error(stochastic_theta_regulari,Y_test,X_test)
print("Accuracy Prediction for Stochastic Gradient descent Algorithm With Regularization")
print(error_stochastic_gda_regulari)

print("--------------------------------------------------------------")
print(" ")
mini_batch_theta_regulari=Mini_Batch_Gradient_descent_algo_regularization(X_bar,Y_train)
print("Theta Value for Mini Batch Gradient descent Algorihtm With Regularization")
print(mini_batch_theta_regulari)
print(" ")
error_mini_batch_regulari=error(mini_batch_theta_regulari,Y_test,X_test)
print("Accuracy Prediction for Mini Batch Gradient descent Algorithm With Regularization")
print(error_mini_batch_regulari)

                   WITH REGULARIZATION                     
 
Theta Value for Batch Gradient descent Algorihtm With Regularization
[ 0.98932068 11.68305443  0.99438859  0.99048681]

Accuracy Prediction for Batch Gradient descent Algorithm With Regularization
30.277880568027697
--------------------------------------------------------------
 
Theta Value for Stochastic Gradient descent Algorihtm With Regularization
[ 1.17681973 12.49848237  0.1428034   0.08300879]
 
Accuracy Prediction for Stochastic Gradient descent Algorithm With Regularization
29.983626517147133
--------------------------------------------------------------
 
Theta Value for Mini Batch Gradient descent Algorihtm With Regularization
[0.98250509 6.90047835 0.98483188 0.9828692 ]
 
Accuracy Prediction for Mini Batch Gradient descent Algorithm With Regularization
47.51233426715228
