In [62]:
import numpy as np

In [63]:
def Input():
  X1=np.array([1,1,1,1,1,1]).reshape(6,1)
  X2=np.array([-1,-1,-1,-1,-1,-1]).reshape(6,1)
  X3=np.array([1,-1,-1,1,1,1]).reshape(6,1)
  X4=np.array([1,1,-1,-1,-1,-1]).reshape(6,1)

  Y1=np.array([1,1,1]).reshape(3,1)
  Y2=np.array([-1,-1,-1]).reshape(3,1)
  Y3=np.array([-1,1,1]).reshape(3,1)
  Y4=np.array([1,-1,1]).reshape(3,1)

  X = np.concatenate((X1, X2, X3, X4), axis = 1)
  # print(X)
  
  Y = np.concatenate((Y1.T, Y2.T, Y3.T, Y4.T), axis = 0) 
  # print(Y)

  return X,Y,X1,X2,X3,X4,Y1,Y2,Y3,Y4

**INPUT GIVEN AND STORED IN X,Y**

In [64]:
X,Y,X1,X2,X3,X4,Y1,Y2,Y3,Y4 = Input()

**WEIGHT CALCULATION**

In [65]:
def Calculate_Weight_Matrix(X,Y):
  w=np.dot(X,Y)
  # print(w)
  return w

In [66]:
Weight = Calculate_Weight_Matrix(X,Y)
print(Weight)

[[2 2 4]
 [4 0 2]
 [2 2 0]
 [0 4 2]
 [0 4 2]
 [0 4 2]]


**TESTING FOR X**

In [67]:
def Testing_X(x,Weight):
  new_y = np.dot(Weight.T,x)

  for i in range(len(new_y)):
    if new_y[i]<0:
      new_y[i]=-1
    else:
      new_y[i]=1

  new_y=np.array(new_y)
  print(new_y)

In [68]:
print("Y1 Value for X1:")
Testing_X(X1,Weight)
print(" ")
print("Y2 Value for X2:")
Testing_X(X2,Weight)
print(" ")
print("Y3 Value for X3:")
Testing_X(X3,Weight)
print(" ")
print("Y4 Value for X4:")
Testing_X(X4,Weight)

Y1 Value for X1:
[[1]
 [1]
 [1]]
 
Y2 Value for X2:
[[-1]
 [-1]
 [-1]]
 
Y3 Value for X3:
[[-1]
 [ 1]
 [ 1]]
 
Y4 Value for X4:
[[ 1]
 [-1]
 [ 1]]


**TESTING FOR Y**

In [69]:
def Testing_Y(y,Weight):
  new_x = np.dot(Weight,y)

  for i in range(len(new_x)):
    if new_x[i]<=0:
      new_x[i]=-1
    else:
      new_x[i]=1

  new_x=np.array(new_x)
  print(new_x)

In [70]:
print("X1 Value for Y1:")
Testing_Y(Y1,Weight)
print(" ")
print("X2 Value for Y2:")
Testing_Y(Y2,Weight)
print(" ")
print("X3 Value for Y3:")
Testing_Y(Y3,Weight)
print(" ")
print("X4 Value for Y4:")
Testing_Y(Y4,Weight)

X1 Value for Y1:
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]]
 
X2 Value for Y2:
[[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [-1]]
 
X3 Value for Y3:
[[ 1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [ 1]]
 
X4 Value for Y4:
[[ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]]


As we can easily see that the BAM model has correctly predicted the Input X and Output Y, what was initially given ,
So we can say that our model is correctly implemented.
