In [71]:
import numpy as np
import matplotlib.pyplot as plt
import csv 

In [72]:
filepath='/Housing Price data set.csv'

# **Storing the value**

In [73]:
price=[]
area=[]
bedroom=[]
bathroom=[]
count=0
with open(filepath, mode ='r') as file:     
   csvFile = csv.reader(file) 
   for lines in csvFile:
     if count==0:
       count=count+1
       continue
     price.append(int(float(lines[1])))
     area.append(int(lines[2]))
     bedroom.append(int(lines[3]))
     bathroom.append(int(lines[4]))

In [74]:
m= round(0.7*len(price))
n=4
X1=np.array(area)
X2=np.array(bedroom)
X3=np.array(bathroom)
Y=np.array(price)

# **Training data and Testing data**

In [75]:
X_train1=X1[:m]
X_train2=X2[:m]
X_train3=X3[:m]
Y_train=Y[:m]
print(X_train1.size)
print(Y_train.size)
X_test1=X1[m+1:]
X_test2=X2[m+1:]
X_test3=X3[m+1:]
Y_test=Y[m+1:]

X_train0=np.ones(m,dtype=int)
X_test0=np.ones(len(X_test1),dtype=int)


382
382


In [ ]:
X_train=[]
for i  in range(m):
  col=[]
  col.append(X_train0[i])
  col.append(X_train1[i])
  col.append(X_train2[i])
  col.append(X_train3[i])
  X_train.append(col)
X_bar=np.array(X_train)
X=np.array([X_train0,X_train1,X_train2,X_train3])

print(len(X_bar))
# X
print(X_bar)
# print(X)
print(Y_train)

# **Batch Gradient Descent Algorithm**

In [224]:
def Batch_Gradient_descent_algo(X,Y_train):
  iteration=1000
  m=X[0].size
  learning_rate=0.0000000001
  theta=np.ones(len(X),dtype=int)
  for i in range(iteration):
    y_pre=np.dot(theta.T,X)
    theta=theta-learning_rate*(1.0/m)*np.dot(y_pre-Y_train,X.T)

  return theta

# **Stochastic Gradient Descent Algorithm**

In [176]:
def combine(X,Y_train):
  cc=[]
  for i in range(len(X)):
    col=[]
    col.append(X[i][0])
    col.append(X[i][1])
    col.append(X[i][2])
    col.append(X[i][3])
    col.append(Y_train[i])
    cc.append(col)
  
  cc=np.array(cc)
  return cc


In [186]:
def split_shuffle(matrix):
  X=[]
  Y=[]
  for i in range(len(matrix)):
    col=[]
    col.append(matrix[i][0])
    col.append(matrix[i][1])
    col.append(matrix[i][2])
    col.append(matrix[i][3])
    X.append(col)
    Y.append(matrix[i][4])
  X=np.array(X)
  Y=np.array(Y)
  return X,Y

In [237]:
def Stochastic_Gradient_descent_algo(X,Y_train):
  shuffle_matrix=combine(X,Y_train)
  np.random.shuffle(shuffle_matrix)
  X,Y_train=split_shuffle(shuffle_matrix)
  m=len(X)
  iteration=1000
  learning_rate=0.0000000001
  thetas=np.ones(X[0].size,dtype=float)

  for it  in range(iteration):
    for i in range(m):
      predic= 1.0*(thetas[0]*X[i][0] + thetas[1]*X[i][1] + thetas[2]*X[i][2] +thetas[3]*X[i][3] - Y_train[i])

      thata0=thetas[0]-1.0*learning_rate*(predic)*X[i][0]
      thata1=thetas[1]-1.0*learning_rate*(predic)*X[i][1]
      thata2=thetas[2]-1.0*learning_rate*(predic)*X[i][2]
      thata3=thetas[3]-1.0*learning_rate*(predic)*X[i][3]

      thetas[0]=thata0
      thetas[1]=thata1
      thetas[2]=thata2
      thetas[3]=thata3
  return thetas

# **Accuracy Prediction**

In [215]:
X_test=[]
for i  in range(len(X_test1)):
  col=[]
  col.append(X_test0[i])
  col.append(X_test1[i])
  col.append(X_test2[i])
  col.append(X_test3[i])
  X_test.append(col)
X_test=np.array(X_test)

In [226]:
def error(theta,Y_test,X_test):
  Y_predic=X_test.dot(theta)   
  error_diff=np.subtract(Y_test,Y_predic)
  abserror_diff=np.absolute(error_diff)
  absolute_error=np.divide(abserror_diff,Y_test)
  mean_ab_error=np.mean(absolute_error)
  return mean_ab_error*100

# **Mini Batch Gradient Descent Algorithm**

In [272]:
def get_batches(X,y,batch_size,i):
    X_batch = X[i:i+batch_size,:]
    y_batch = y[i:i+batch_size]    
    return X_batch, y_batch

In [302]:
def Mini_Batch_Gradient_descent_algo(X,Y_train):
  batch_size=10
  num_batches = int(X.shape[0]/batch_size) 
  theta=np.ones(X[0].size,dtype=float)
  # print(num_batches)
  alpha=0.000000001
  for i in range(0,num_batches):
    X_batch, y_batch = get_batches(X,Y_train,batch_size,i)
    predic = np.dot(X_batch,theta)
    theta = theta - alpha * np.dot(X_batch.T,predic - y_batch)/batch_size
  
  thet=[]
  thet.append(theta[0])
  thet.append(theta[1])
  thet.append(theta[2])
  thet.append(theta[3])
  
  thet=np.array(thet)
  return thet

# **Main**

In [307]:
batch_theta=Batch_Gradient_descent_algo(X,Y_train)
print("Theta Value for Batch Gradient descent Algorihtm")
print(batch_theta)
print("")
error_batch_gda=error(batch_theta,Y_test,X_test)
print("Accuracy Prediction for Batch Gradient descent Algorithm")
print(error_batch_gda)

print("--------------------------------------------------------------")
print(" ")
stochastic_theta=Stochastic_Gradient_descent_algo(X_bar,Y_train)
print("Theta Value for Stochastic Gradient descent Algorihtm")
print(stochastic_theta)
print(" ")
error_stochastic_gda=error(stochastic_theta,Y_test,X_test)
print("Accuracy Prediction for Stochastic Gradient descent Algorithm")
print(error_stochastic_gda)

print("--------------------------------------------------------------")
print(" ")
mini_batch_theta=Mini_Batch_Gradient_descent_algo(X_bar,Y_train)
print("Theta Value for Mini Batch Gradient descent Algorihtm")
print(mini_batch_theta)
print(" ")
error_mini_batch=error(mini_batch_theta,Y_test,X_test)
print("Accuracy Prediction for Mini Batch Gradient descent Algorithm")
print(error_mini_batch)

Theta Value for Batch Gradient descent Algorihtm
[ 1.0023332  11.72948415  1.00742127  1.00350479]

Accuracy Prediction for Batch Gradient descent Algorithm
30.229953002026335
--------------------------------------------------------------
 
Theta Value for Stochastic Gradient descent Algorihtm
[ 1.1658957  12.47206562  1.6568209   1.37175233]
 
Accuracy Prediction for Stochastic Gradient descent Algorithm
29.972431812687944
--------------------------------------------------------------
 
Theta Value for Mini Batch Gradient descent Algorihtm
[1.00133967 6.96105709 1.00368276 1.00170685]
 
Accuracy Prediction for Mini Batch Gradient descent Algorithm
47.159202904283795
